### ISSUE TITLE
Data Exploration

### ISSUE THREAD

**Issue by billsioros** [AristiPap/Identification-of-human-activities-in-the-Amazon-forests#3]
- Check if the dataset is balanced (Label Exploration, Correlation Matrices, Histogram, etc...)
- Showcase a few images corresponding to different labels.
- Learning Rate / Train vs Validation
- (Optional) After having the CNN model train, explore what the individual CNN layers are capable of recognizing

**Comment by AristiPap** [comment]
Completed.
